name-template: 'v$NEXT_MINOR_VERSION 🎉'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Fixes'
    labels:
      - 'bugfix'
      - 'hotfix'
      - 'fix'
      - 'bug'
  - title: '🌱 Updates'
    labels:
      - 'dependencies'
      - 'update'
      - 'dependency-update'
exclude-labels:
  - 'skip-changelog'
  - 'invalid'
template: |
  ## 📢 What's changed?
  $CHANGES
  ## 👬 Contributors
  $CONTRIBUTORS
  ## 🔙 Previous
  $PREVIOUS_TAG
