name: release-drafter

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
